[package]
name = "bevy_terrain"
description = "Terrain Rendering for the Bevy Engine."
version = "0.1.0-dev"
license = "MIT OR Apache-2.0"
edition = "2024"
categories = ["game-engines", "rendering", "graphics"]
keywords = ["gamedev", "graphics", "bevy", "terrain"]
exclude = ["assets/*"]
readme = "README.md"
authors = ["Kurt Kühnert <kurt@kuehnert.dev>"]
repository = "https://github.com/kurtkuehnert/bevy_terrain"

[workspace]
members = ["preprocess"]

[features]
default = ["high_precision", "rand"]
high_precision = ["dep:big_space"]
rand = ["dep:rand"]
metal_capture = ["dep:metal", "dep:wgpu-core"]
unstable = ["wesl"]
wesl = ["bevy/shader_format_wesl"]

[dependencies]
tiff = "0.11"
bytemuck = "1.24"
bitflags = "2.10"
anyhow = "1.0"
serde = "1.0"
async-channel = "2.5"
bevy = "0.18"
bevy_common_assets = { version = "0.15", features = ["ron"] }
ndarray = "0.17"
itertools = "0.14"
derive_more = { version = "2.1", features = ["from"] }
slab = "0.4"
strum = "0.27"
strum_macros = "0.27"
big_space = { git = "https://github.com/victor7543/big_space", branch = "bevy-0.18-port", features = ["i32"], optional = true }
rand = { version = "0.9", optional = true }
ron = "0.12"
metal = { version = "0.33", optional = true }
wgpu-core = { version = "28.0", optional = true }

[[example]]
name = "spherical"
path = "examples/spherical.rs"
required-features = ["high_precision"]

[[example]]
name = "precision_demo"
path = "examples/precision_demo.rs"
required-features = ["high_precision", "rand"]
