[package]
name = "bevy_terrain_preprocess"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_terrain = { path = "..", features = ["high_precision"] }
gag = "1.0.0"
tiff-core = "0.4"
tiff-reader = "0.4"
tiff-writer = "0.4"
geotiff-reader = "0.4"
bevy_math = "0.18"
itertools = "0.14.0"
thiserror = "2.0.8"
num = "0.4"
rayon = "1.10.0"
thread_local = "1.1.8"
clap = { version = "4.5.17", features = ["derive"] }
indicatif = { version = "0.18.0", features = ["rayon"] }
ndarray = "0.17.2"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
  'cfg(gdal_major_ge_3)',
  'cfg(gdal_major_ge_4)',
  'cfg(gdal_minor_ge_5)',
  'cfg(gdal_minor_ge_7)',
] }

[[example]]
name = "preprocess_spherical"
path = "examples/preprocess_spherical.rs"

[[example]]
name = "preprocess_los"
path = "examples/preprocess_los.rs"

[[example]]
name = "preprocess_earth"
path = "examples/preprocess_earth.rs"

[[example]]
name = "preprocess_swiss"
path = "examples/preprocess_swiss.rs"
